### ISSUE TITLE
don't gitignore the dist-folder

### ISSUE THREAD

**Issue by Suven** [ember-cli/rfcs#37]
Hi,

when generating a new ember-app the cli will create a reasonable starting-structure and default .gitignore.

There are pre-populated and empty folders in that structure, depending on how much sense it makes for those folders.

One folder that is not currently created by default and also ignored, is the distfolder. Although it makes sense to ignore the contents of the dist-folder, I would like to argue for the idea that the folder itself belongs to an ember-project:
1. You are very very likely to create it anyway while developing. Having that empty folder in place when cloning a repo makes sure that it's name is reserved. If you happen to create a dist-folder yourself and add files to it, ember build will erase all your contents. This might be an obvious fact for ember-devs buuut, in my point of view, speaks for reserving that special folder right from the beginning.
2. Projects like ember-cli-cordova or ember-electron rely on that folder being present. Cordova, for example, will contain a symlink www to the dist-folder. If the distfolder does not exist, the symlink is broken which results in cordova not recognizing the cordova-subdir as a valid cordova-project. The common workaround for this is to `mkdir dist` either by hand or from within the build-chain. To prevent having the contributors creating the dir before they can run things like 'cordova prepare', one might have the idea to checkin the dist-folder into git and then ignore just it's contents via a .gitignore inside it. But since `ember build` will delete the contents of dist, that gitignore will also be deleted.

**Comment by stefanpenner** [comment]
I'm unsure if this addons should link dist. They should likely use --output-path

**Comment by nathanhammond** [comment]
Hey @Suven! We discussed this in today's ember-cli team meeting. To rephrase your goal we believe that you want to have a single place inside of an application guaranteed to always exist so that you can have a persistent symlink external to the project have a "reference" to that folder.

Since the entire existence of the output folder is considered transient by ember-cli it's not a good fit for your proposed pattern. It's part of several typical workflows to `rm -rf dist`, so we already don't feel like we can provide guarantees as to its existence even if we accounted for it internally inside of ember-cli.

We encourage you to explore `--output-path` and see if you can make that do what you want (and target folders external to the application). We're excited to work with you to make that support your needs. We imagine that the integration with external workflows should match something similar to what ember-cli-deploy does, which essentially wraps `ember build` and feeds that into Cordova/Electron.

We're also working to identify a core extensibility primitive which should make it easier for you to tweak behaviors inside of addons.

**Comment by Suven** [comment]
Thanks for your consideration and explanation (:

I'll look into the output-path alternatives
