### ISSUE TITLE
ember move (mv)

### ISSUE THREAD

**Issue by floqqi** [ember-cli/rfcs#38]
See https://github.com/ember-cli/ember-cli/issues/5596.

Maybe [https://github.com/trabus/ember-cli-rename](https://github.com/trabus/ember-cli-rename) could become part of the ember-cli core?

**Comment by nathanhammond** [comment]
Hey @floqqi! We discussed this in today's ember-cli team meeting (which included @trabus). We don't disagree that this is a valuable utility (clearly), and would like for this to exist. However, we have a few basic concerns and don't believe that this is a good fit for inclusion into ember-cli core at this time:
- By rule we can't make this perfect for reasons of "halting problem" ... it will only ever be "best effort," which is below the bar we want to set for core features. For example, do you simply rename the files or do you actually change all of the `link-to` components in the application templates? What do you do for variables that hardcode route names? Getting the majority is a great space for an addon to live as it will scratch the itch for most.
- We want the core of ember-cli to remain focused on the essentials for building an Ember application and be choosy about how we invest our time as a team. This is part of the reason we've designed ember-cli to be extensible in the first place so that we don't have to single-handedly maintain the entire ecosystem.
- Speaking of which, this is incredibly well-suited for being built as an addon as it doesn't need to integrate with other portions of ember-cli itself.

We'll continue to monitor activity on ember-cli-rename and would encourage you to get involved with that project! If it continues to mature and "best effort" becomes "almost every scenario accounted for" we are willing to reconsider and possibly include the addon as part of the default ember-cli distribution.
